default: &default
  username: jam
  password: llq123@jam
  host: localhost
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: jam_test_v11
production:
  <<: *default
  database: jam_test_v11
test:
  <<: *default
  database: jam_test_v11
